### ISSUE TITLE
Request to release pretrained models

### ISSUE THREAD

**Issue by huangqiusheng** [facebookresearch/StyleNeRF#1]
We're glad you finally released the code, this is a great job. Can you release the pretrained models, especially the CompCars model, for a better experience?

**Comment by MultiPath** [comment]
Hi, I will add the link of the pretrained models probably by next week.
Thanks

**Comment by muhammad-ahmed-ghani** [comment]
@MultiPath  Can you upload the links for pretrained model soon ?

**Comment by MultiPath** [comment]
Hi, I am sorry for the delay. I had some issues with my AWS account which will serves our pretrained model and data. I need to wait people to fix it before I can upload the checkpoints.

**Comment by MultiPath** [comment]
Hi, I have added one checkpoint of FFHQ. In the following days, I am also adding more checkpoints to huggingface models. Thanks for your very kind patience!

**Comment by yaoyuan13** [comment]
> 

Hi, when I use your newly uploaded checkpoints to run inference code, an error occurs "_pickle.UnpicklingError: invalid load key, 'v'." Do you known why this happens?
