### ISSUE TITLE
Bug? Wrong shape

### ISSUE THREAD

**Issue by lelechen63** [facebookresearch/StyleNeRF#10]
https://github.com/facebookresearch/StyleNeRF/blob/03d3800500385fffeaa2df09fca649edb001b0bb/apps/inversion.py#L119

if we set encoder_z=True, the shape of zs output from E is [1,17,512], but the mapping network can only accept input with 2 dimensions ([1, 512]). Different from stylegan, the value of each z  of zs is not the same (zs[:,0,:] != zs[:,1,:]). So, we can not squeeze zs from [1,17,512] into [1,512].

**Comment by MultiPath** [comment]
Again, the inversion part of the code is not fully cleaned and tested. I think we tried both ways, and inverting either in W space or W+ space.

**Comment by lelechen63** [comment]
SOlVED. Thanks！
