### ISSUE TITLE
Question for Upsample operation (Equation 7 in paper)

### ISSUE THREAD

**Issue by LeoXing1996** [facebookresearch/StyleNeRF#11]
Thanks for the great work. However, I have a question about the upsample operation.
In the released code, the `Upsample` operation seems to be the following code:

https://github.com/facebookresearch/StyleNeRF/blob/03d3800500385fffeaa2df09fca649edb001b0bb/training/networks.py#L481-L491

Why is the above code equal to the upsample operation mentioned in the paper? Looking forward to your reponse.

**Comment by MultiPath** [comment]
Hi, "nn_cat" is another form of upsampling function which works similarly to the original paper, which is "pixelshuffle"
https://github.com/facebookresearch/StyleNeRF/blob/main/training/networks.py#L359

You can always switch the upsampler function in the config.
They work almost the same. The good advantage of using "nn_cat“ is that it supports rotation in the image plane, while pixelshuffle does not.
![image](https://user-images.githubusercontent.com/5780274/158878433-a45dc424-de7d-4430-a62f-1bf43b9eb9f0.png)
(pixelshuffle in the original paper)
![image](https://user-images.githubusercontent.com/5780274/158878623-e01edc09-5d3c-4e6f-b5a6-51d67708bb02.png)
(nn_cat)
