### ISSUE TITLE
some error when inference

### ISSUE THREAD

**Issue by 41xu** [facebookresearch/StyleNeRF#16]
Hi! Thanks your amazing work!
I try to render your pretrained model as described in https://github.com/facebookresearch/StyleNeRF/#render-the-pretrained-model using your ffhq_512.pkl. But it failed!
The error message is as follows:
```
legacy.py", line 21, in load_network_pkl
    data = _LegacyUnpickler(f).load()
_pickle.UnpicklingError: invalid load key, 'v'.
```
Is there anything wrong with your hugging face pretrianed model or somewhere else?
Looking forward to your reply!

**Comment by 41xu** [comment]
@MultiPath

**Comment by MultiPath** [comment]
Hmm I never saw this. Are you following the same environment to run the code?

**Comment by 41xu** [comment]
> 

Yes, I install a python 3.7.11 environment and follow the requirements of the package.

**Comment by 41xu** [comment]
Hi! I try to download the model again from huggingface and the problem fixed. Thanks for your help!
