### ISSUE TITLE
Can't get anything to work after installation seemed to go smoothly

### ISSUE THREAD

**Issue by Wythneth** [facebookresearch/StyleNeRF#2]
So I'm a little bit of  a noob when it comes to installing things like this (although I have succesfully in the past).
I followed all of the instructions, and everything seemed to install fine with no issues.

After installing the requirements, none of the other commands seem to work.

Is there  a detailed guide anywhere as to how to get everything set up correctly?

**Comment by MultiPath** [comment]
Hi, can you give some screenshots about what the errors you met?
Thanks

**Comment by Wythneth** [comment]
I feel it might be an issues with how I'm using this. I'm not sure how to correctly write out the paths in the code used for training. I can get the GUI opening and everything. I'm just confused about where I put my image and output folders. I'm not exactly a coder, so I'm not sure how to correctly enter in the output directory and the image directory.

Sorry if this is frustrating for you to read through. I'm fairly in-experienced

**Comment by MultiPath** [comment]
Ok. I will add more instructions about the data and how to execute the code together with pretrained model in this weekend. Thanks for pointing out!

**Comment by Wythneth** [comment]
No worries at all! This tool looks incredible and I'd love to give it a try. I'll check back in next week to try out your instructions. Thanks :)
