### ISSUE TITLE
Training config of EG3D

### ISSUE THREAD

**Issue by MrTornado24** [facebookresearch/StyleNeRF#3]
Thanks for releasing the code! I tried training eg3d from scratch following the config file "stylenerf_ffhq_eg3d" , but it cannot converge. How should I change the config file?

**Comment by MultiPath** [comment]
Hi, do you mind to have some screenshots or results to help inspect?

Also, this "eg3d" config is just my own re-implementation with some special modifications. It is not the original NIVDIA paper.
Thanks

**Comment by MrTornado24** [comment]
Thanks! My training command is: "CUDA_VISIBLE_DEVICES=0 python run_train.py outdir=training-runs data=data/ffhq/images1024x1024 resolution=512 model=stylenerf_ffhq_eg3d". The screenshot of training process is:
![image](https://user-images.githubusercontent.com/45503891/157999441-a6e736a3-7a9c-4662-b188-07908372fb69.png)
