### ISSUE TITLE
Fine-tune on MetFaces dataset.

### ISSUE THREAD

**Issue by zhanglonghao1992** [facebookresearch/StyleNeRF#32]
How to fine tune the model trained on FFHQ to small datasets like MetFaces? Do I need to freeze some parameters?

**Comment by abhay-sheshadri** [comment]
Did you manage to find a solution?

**Comment by zhanglonghao1992** [comment]
@abhay-sheshadri No need to freeze any parameter, just fine-tune the model like the stylegan.
