### ISSUE TITLE
Change Facial expressions?

### ISSUE THREAD

**Issue by Echolink50** [facebookresearch/StyleNeRF#37]
I was wondering if the visualizer allows you to change the facial expressions? I messed around with the demo and it's fine but 90 percent of the faces are smiling or showing teeth which is not what I want. I tried to look at the image of the visualizer GUI but I couldn't tell if there was any input to change the facial expression so I figured I would ask before I go through all the effort to install stylenerf. Thanks everyone

**Comment by MultiPath** [comment]
Yes, the model is not fully 3D consistent because of the dataset bias.
