### ISSUE TITLE
Why are you doing this?

### ISSUE THREAD

**Issue by jeffmarshall** [facebookresearch/StyleNeRF#4]
Hello,

I'm a software engineer and a curious onlooker. I've watched as AI has developed in ways that make it hard to differentiate from genuine intelligence, and mostly, I can see how each development may benefit society. But when it comes to AI-generated human faces, I'm at a loss. I can think of a million ways that this could be used to make the world worse, and I can only think of one or two ways this will make things marginally better, financially, for a handful of people. So, I feel compelled to ask; why are you doing this?

**Comment by MultiPath** [comment]
These faces are generated from random seeds. So they are not real. I think if one day we can generate perfect fake faces looks like real people, everyone can train their new applications on top of them without worrying about the privacy issues, and it in turn has more contributions to the world.
