### ISSUE TITLE
importerror: cannot import name 'dist' from 'math'

### ISSUE THREAD

**Issue by TiankaiHang** [facebookresearch/StyleNeRF#40]
https://github.com/facebookresearch/StyleNeRF/blob/7a8cfd871924a61faf4a639b91304d16eed0e286/run_train.py#L4

**Comment by jxhuang0508** [comment]
The same issue. Have u solve this issue?

**Comment by TiankaiHang** [comment]
> 

Just comment it

**Comment by MultiPath** [comment]
I think it is due to Python version.
