### ISSUE TITLE
How to get the high resolution result

### ISSUE THREAD

**Issue by apriljt** [facebookresearch/StyleNeRF#45]
Hello I have a issue when I want to train my own model with my dataset.
The resolution of my dataset is 10241024 and the output of my model turn out to be 3232 and when I try for 10 hour it became to 64*64 resolution. I have no idea about this growth resolution and I want to get a high resolution result as the same as my training dataset how to do it? Can you help me?
Thank you!

**Comment by MultiPath** [comment]
The model is trained in a progressive way. It will progressively increase the resolution of the generate images.
It was controlled by setting:
https://github.com/facebookresearch/StyleNeRF/blob/main/conf/model/stylenerf_ffhq.yaml#L108
For example, the model will stay at 32x32 for the first 500K images. Then the model will increase the resolution until the target resolution at 5M images.
