### ISSUE TITLE
hi After watching this demo, I think it's amazing. Will the pre-trained model be given?

### ISSUE THREAD

**Issue by baixinping618** [facebookresearch/StyleNeRF#6]
hi After watching this demo, I think it's amazing. Will the pre-trained model be given?

**Comment by acoMCMXCVI** [comment]
#1

**Comment by MultiPath** [comment]
Hi, I am sorry for the delay. I had some issues with my AWS account which will serves our pretrained model and data. I need to wait people to fix it before I can upload the checkpoints.

**Comment by MultiPath** [comment]
Hi, I have added one checkpoint of FFHQ. In the following days, I am also adding more checkpoints to huggingface models. Thanks for your very kind patience!
